layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 0
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: aipetrov
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: antonipetrov
  # unsplash: your_username
  # vk: your_username
  website: https://www.ebi.ac.uk/about/people/anton-petrov
  orcid: 0000-0001-7279-2682
  # youtube: your_username

topics:
  - name: RNAcentral
    web_url: https://rnacentral.org
    image_url: https://rnacentral.org/static/img/logo/rnacentral-logo.png

  - name: Rfam
    web_url: http://rfam.org
    image_url: https://raw.githubusercontent.com/Rfam/rfam-docs/master/docs/source/images/rfam.ico

  - name: RNA 3D Hub
    web_url: http://rna.bgsu.edu/rna3dhub
    image_url: https://pbs.twimg.com/profile_images/1832011010/logo_400x400.png
